"""add account_number and external_ref

Revision ID: 253d648aacc4
Revises: b1611eae968c
Create Date: 2026-08-01 14:55:56.829978

"""
from alembic import op
import sqlalchemy as sa


revision = '253d648aacc4'
down_revision = 'b1611eae968c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_number', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('external_ref', sa.String(length=150), nullable=True))
    op.create_unique_constraint('uq_transactions_external_ref', 'transactions', ['external_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_external_ref', 'transactions', type_='unique')
    op.drop_column('transactions', 'external_ref')
    op.drop_column('accounts', 'account_number')
    # ### end Alembic commands ###
